# Generated by Django 3.2 on 2024-05-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campo1', models.CharField(max_length=100)),
                ('valor1', models.IntegerField()),
            ],
        ),
    ]
